---

- name: Ensure chrony is installed
  dnf:
    name: chrony
    state: present
  become: yes

- name: set timezone
  command: timedatectl set-timezone UTC

#- name: set timezone in /etc/sysconfig/clock
#  lineinfile: dest=/etc/sysconfig/clock regexp="^ZONE" line="ZONE={{timezone_area}}/{{timezone_city}}"
#  register: timezone

## XXX Could be in common... ###
#- name: setup timezone link
#  shell: ln -sf /usr/share/zoneinfo/{{timezone_area}}/{{timezone_city}} /etc/localtime
#  when: timezone.changed

#- name: ensure ntpd is running
#  service: name=ntpd state=started

- name: enable cronyd on rhel8
  service: name=chronyd state=started  # fails if service already running, which is dumb

- name: Install python3-pip
  dnf:
    name: python3-pip
    state: present
  become: yes

- name: Install SELinux Python bindings
  dnf:
    name: python3-libselinux
    state: present
  become: yes

- name: disable selinux
  command: setenforce 0

- debug:
    var: ansible_facts.interfaces

- name: the network or subnet address from which the clients are allowed to connect.
  lineinfile: dest=/etc/chrony.conf line="allow {{ ansible_ens6.ipv4.network }}"

#- name: restart cronyd on rhel8
#  service: name=chronyd state=restarted
